version: "3.9"

services:
  student01:
    image: debian-student:latest
    container_name: student01
    restart: unless-stopped
    ports:
      - "2221:22"
      - "5433:5432"
    volumes:
      - student01_home:/home/debian

  student02:
    image: debian-student:latest
    container_name: student02
    restart: unless-stopped
    ports:
      - "2222:22"
      - "5434:5432"
    volumes:
      - student02_home:/home/debian

  student03:
    image: debian-student:latest
    container_name: student03
    restart: unless-stopped
    ports:
      - "2223:22"
      - "5435:5432"
    volumes:
      - student03_home:/home/debian

  student04:
    image: debian-student:latest
    container_name: student04
    restart: unless-stopped
    ports:
      - "2224:22"
      - "5436:5432"
    volumes:
      - student04_home:/home/debian

  student05:
    image: debian-student:latest
    container_name: student05
    restart: unless-stopped
    ports:
      - "2225:22"
      - "5437:5432"
    volumes:
      - student05_home:/home/debian

  student06:
    image: debian-student:latest
    container_name: student06
    restart: unless-stopped
    ports:
      - "2226:22"
      - "5438:5432"
    volumes:
      - student06_home:/home/debian

  student07:
    image: debian-student:latest
    container_name: student07
    restart: unless-stopped
    ports:
      - "2227:22"
      - "5439:5432"
    volumes:
      - student07_home:/home/debian

  student08:
    image: debian-student:latest
    container_name: student08
    restart: unless-stopped
    ports:
      - "2228:22"
      - "5440:5432"
    volumes:
      - student08_home:/home/debian

  student09:
    image: debian-student:latest
    container_name: student09
    restart: unless-stopped
    ports:
      - "2229:22"
      - "5441:5432"
    volumes:
      - student09_home:/home/debian

  student10:
    image: debian-student:latest
    container_name: student10
    restart: unless-stopped
    ports:
      - "2230:22"
      - "5442:5432"
    volumes:
      - student10_home:/home/debian

volumes:
  student01_home:
  student02_home:
  student03_home:
  student04_home:
  student05_home:
  student06_home:
  student07_home:
  student08_home:
  student09_home:
  student10_home:
